
-- Mark Six Example
CREATE TABLE MARKSIX (
	NUM INTEGER
);
INSERT INTO MARKSIX VALUES (1);
INSERT INTO MARKSIX VALUES (2);
INSERT INTO MARKSIX VALUES (3);
INSERT INTO MARKSIX VALUES (4);
INSERT INTO MARKSIX VALUES (5);
INSERT INTO MARKSIX VALUES (6);
INSERT INTO MARKSIX VALUES (7);
INSERT INTO MARKSIX VALUES (8);
INSERT INTO MARKSIX VALUES (9);
INSERT INTO MARKSIX VALUES (10);
INSERT INTO MARKSIX VALUES (11);
INSERT INTO MARKSIX VALUES (12);
INSERT INTO MARKSIX VALUES (13);
INSERT INTO MARKSIX VALUES (14);
INSERT INTO MARKSIX VALUES (15);
INSERT INTO MARKSIX VALUES (16);
INSERT INTO MARKSIX VALUES (17);
INSERT INTO MARKSIX VALUES (18);
INSERT INTO MARKSIX VALUES (19);
INSERT INTO MARKSIX VALUES (20);
INSERT INTO MARKSIX VALUES (21);
INSERT INTO MARKSIX VALUES (22);
INSERT INTO MARKSIX VALUES (23);
INSERT INTO MARKSIX VALUES (24);
INSERT INTO MARKSIX VALUES (25);
INSERT INTO MARKSIX VALUES (26);
INSERT INTO MARKSIX VALUES (27);
INSERT INTO MARKSIX VALUES (28);
INSERT INTO MARKSIX VALUES (29);
INSERT INTO MARKSIX VALUES (30);
INSERT INTO MARKSIX VALUES (31);
INSERT INTO MARKSIX VALUES (32);
INSERT INTO MARKSIX VALUES (33);
INSERT INTO MARKSIX VALUES (34);
INSERT INTO MARKSIX VALUES (35);
INSERT INTO MARKSIX VALUES (36);
INSERT INTO MARKSIX VALUES (37);
INSERT INTO MARKSIX VALUES (38);
INSERT INTO MARKSIX VALUES (39);
INSERT INTO MARKSIX VALUES (40);
INSERT INTO MARKSIX VALUES (41);
INSERT INTO MARKSIX VALUES (42);
INSERT INTO MARKSIX VALUES (43);
INSERT INTO MARKSIX VALUES (44);
INSERT INTO MARKSIX VALUES (45);
INSERT INTO MARKSIX VALUES (46);
INSERT INTO MARKSIX VALUES (47);
INSERT INTO MARKSIX VALUES (48);
INSERT INTO MARKSIX VALUES (49);

SELECT *
FROM MARKSIX NUM1 INNER JOIN MARKSIX NUM2 ON NUM1.NUM <> NUM2.NUM -- 49 X 49
INNER JOIN MARKSIX NUM3 ON NUM1.NUM <> NUM3.NUM
INNER JOIN MARKSIX NUM4 ON NUM1.NUM <> NUM4.NUM;

-- ALTERNATIVE FOR INNER JOIN
-- RESULT MAY HAVE SAME COMBINATION IN TERMS OF NUMBER
-- 42 7 6 2
-- 2 6 7 42
SELECT *
FROM MARKSIX NUM1, MARKSIX NUM2, MARKSIX NUM3, MARKSIX NUM4 -- 49 X 49 X 49 X 49
WHERE NUM1.NUM <> NUM2.NUM
AND NUM1.NUM <> NUM3.NUM
AND NUM1.NUM <> NUM4.NUM
AND NUM2.NUM <> NUM3.NUM
AND NUM2.NUM <> NUM4.NUM
AND NUM3.NUM <> NUM4.NUM;

-- CLASS MARKSIX (NUM1, NUM2, NUM3, NUM4, NUM5, NUM6) -> EQUALS()