-- CREATE DATABASE
CREATE DATABASE SQL_EXERCISE_1;
USE SQL_EXERCISE_1;



-- CREATE TABLES
-- REGIONS
CREATE TABLE REGIONS (
	REGION_ID INTEGER PRIMARY KEY, -- PRIMARY KEY
    REGION_NAME VARCHAR(25) 
);
 -- COUNTRIES
CREATE TABLE COUNTRIES (
	COUNTRY_ID VARCHAR(2) PRIMARY KEY, -- PRIMARY KEY
    COUNTRY_NAME VARCHAR(40),
    REGION_ID INTEGER, -- FOREIGN KEY REGIONS.REGION_ID
    FOREIGN KEY (REGION_ID) REFERENCES REGIONS(REGION_ID)
);
-- LOCATIONS
CREATE TABLE LOCATIONS (
	LOCATION_ID INTEGER PRIMARY KEY, -- PRIMARY KEY
    STREET_ADDRESS VARCHAR(25),
    POSTAL_CODE VARCHAR(12),
    CITY VARCHAR(30),
    STATE_PROVINCE VARCHAR(12),
    COUNTRY_ID VARCHAR(2), -- FOREIGN KEY COUNTRIES.COUNTRY_ID
    FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRIES(COUNTRY_ID)
);
-- DEPARTMENTS
CREATE TABLE DEPARTMENTS (
	DEPARTMENT_ID INTEGER PRIMARY KEY, -- PRIMARY KEY
    DEPARTMENT_NAME VARCHAR(30),
    MANAGER_ID INTEGER,
    LOCATION_ID INTEGER, -- FOREIGN KEY LOCATIONS.LOCATION_ID
    FOREIGN KEY (LOCATION_ID) REFERENCES LOCATIONS(LOCATION_ID)
);
-- JOBS
CREATE TABLE JOBS (
	JOB_ID VARCHAR(10) PRIMARY KEY, -- PRIMARY KEY
    JOB_TITLE VARCHAR(35),
    MIN_SALARY INTEGER,
    MAX_SALARY INTEGER
);
-- EMPLOYEES
CREATE TABLE EMPLOYEES (
	EMPLOYEE_ID INTEGER PRIMARY KEY, -- PRIMARY KEY
    FIRST_NAME VARCHAR(20),
    LAST_NAME VARCHAR(25),
    EMAIL VARCHAR(25),
    PHONE_NUMBER VARCHAR(25),
    HIRE_DATE DATE,
    JOB_ID VARCHAR(10), -- FOREIGN KEY JOBS.JOB_ID
    SALARY INTEGER,
    COMMISSION_PCT INTEGER,
    MANAGER_ID INTEGER,
    DEPARTMENT_ID INTEGER, -- FOREIGN KEY DEPARTMENTS.DEPARTMENT_ID
    FOREIGN KEY (JOB_ID) REFERENCES JOBS(JOB_ID),
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID)
);
-- JOB_HISTORY
CREATE TABLE JOB_HISTORY (
	EMPLOYEE_ID INTEGER, -- FOREIGN KEY EMPLOYEES.EMPLOYEE_ID
    START_DATE DATE,
    END_DATE DATE,
	JOB_ID VARCHAR(10), -- FOREIGN KEY JOBS.JOB_ID
    DEPARTMENT_ID INTEGER, -- FOREIGN KEY DEPARTMENTS.DEPARTMENT_ID
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID),
    FOREIGN KEY (JOB_ID) REFERENCES JOBS(JOB_ID),
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID)
);

DROP TABLE REGIONS;
DROP TABLE COUNTRIES;
DROP TABLE LOCATIONS;
DROP TABLE DEPARTMENTS;
DROP TABLE JOBS;
DROP TABLE EMPLOYEES;
DROP TABLE JOB_HISTORY;


