DROP DATABASE IF EXISTS SQL_EXERCISE4;
SHOW DATABASES;
CREATE DATABASE SQL_EXERCISE4;
USE SQL_EXERCISE4;

DROP TABLE IF EXISTS PLAYERS;
DROP TABLE IF EXISTS MATCHES;
SHOW TABLES;

CREATE TABLE PLAYERS (
	PLAYER_ID INTEGER NOT NULL UNIQUE,
    GROUP_ID INTEGER NOT NULL,
    PRIMARY KEY (PLAYER_ID)
);

CREATE TABLE MATCHES (
	MATCH_ID INTEGER NOT NULL UNIQUE,
    FIRST_PLAYER INTEGER NOT NULL,
    SECOND_PLAYER INTEGER NOT NULL,
    FIRST_SCORE INTEGER NOT NULL,
    SECOND_SCORE INTEGER NOT NULL,
    FOREIGN KEY (FIRST_PLAYER) REFERENCES PLAYERS(PLAYER_ID),
    FOREIGN KEY (SECOND_PLAYER) REFERENCES PLAYERS(PLAYER_ID)
);

INSERT INTO PLAYERS VALUES (20, 2);
INSERT INTO PLAYERS VALUES (30, 1);
INSERT INTO PLAYERS VALUES (40, 3);
INSERT INTO PLAYERS VALUES (45, 1);
INSERT INTO PLAYERS VALUES (50, 2);
INSERT INTO PLAYERS VALUES (65, 1);
SELECT * FROM PLAYERS;

INSERT INTO MATCHES VALUES (1, 30, 45, 10, 12);
INSERT INTO MATCHES VALUES (2, 20, 50, 5, 5);
INSERT INTO MATCHES VALUES (13, 65, 45, 10, 10);
INSERT INTO MATCHES VALUES (5, 30, 65, 3, 15);
INSERT INTO MATCHES VALUES (42, 45, 65, 8, 4);
SELECT * FROM MATCHES;

--
WITH
FIRST_PLAYER_SCORE AS (
	SELECT
		MATCH_ID,
        FIRST_PLAYER AS PLAYER_ID,
        FIRST_SCORE AS SCORE
	FROM MATCHES
),
SECOND_PLAYER_SCORE AS (
	SELECT
		MATCH_ID,
        SECOND_PLAYER AS PLAYER_ID,
        SECOND_SCORE AS SCORE
	FROM MATCHES
),
UNION_PLAYER_SCORE AS (
	SELECT * FROM FIRST_PLAYER_SCORE
	UNION ALL
	SELECT * FROM SECOND_PLAYER_SCORE
),
JOIN_GROUP_PLAYER_SCORE AS (
	SELECT
		P.GROUP_ID,
        P.PLAYER_ID,
        U.SCORE
    FROM PLAYERS P LEFT JOIN UNION_PLAYER_SCORE U ON P.PLAYER_ID = U.PLAYER_ID
)
SELECT * FROM JOIN_GROUP_PLAYER_SCORE;

-- SELECT * FROM FIRST_PLAYER_SCORE;
-- SELECT * FROM SECOND_PLAYER_SCORE;
-- SELECT * FROM UNION_PLAYER_SCORE;  
